/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
export const awsExports = {
  "REGION":"us-east-1",
  "USER_POOL_ID": "us-east-1_IKeeqtB0l" ,
  "USER_POOL_CLIENT_ID":"46523n61f4g9f3khip8s7ovl3u"
};

